#URL of MySQL in azure
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=${AZURE_KEY_VAULT_ENDPOINT}
spring.datasource.url= ${datasource-url}
#admin username of MySQL
spring.datasource.username=${datasource-username}
#password of admin of MySQL 
spring.datasource.password= ${datasource-password}
spring.jpa.hibernate.ddl-auto=none
management.endpoints.web.exposure.include=health,info

# environment variable with a default value
spring.ai.openai.base-url=${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions}

# secret from Azure Key Vault
spring.ai.openai.api-key=${ai.openai.api-key:your-openai-api-key}













